### ISSUE TITLE
Pass custom map data

### ISSUE THREAD

**Issue by joranmulderij** [greensopinion/dart-vector-tile-renderer#37]
I was unable to figure out how to provide custom map data. Could you please explain or create some documentation for anyone who is trying to do things that are not in the example?

**Comment by amenk** [comment]
Are you talking about locally stored tiles (.pbf files) ? Or adding markers on top of the tiles ? Or something else? What is your use case?

**Comment by ibrierley** [comment]
I'd be quite interested in this actually. I'm guessing it revolves around TileFactory create, but its not quite clear, if one has a set of features in any form (eg a list, or json or whatever) containing coordinates in tile space, if it would be feasible to create a Tile with a set of TileFeatures and have it display (rather than needing to pass any protobuf stuff) ?

**Comment by greensopinion** [comment]
Looks like a cool project! 

The scope of this library is to draw vector tiles. If that's all you want to do, then hopefully what's here is enough! 

To pass custom map data, you just need to produce protobuf tiles with the data that you want. [the mapbox docs](https://docs.mapbox.com/data/tilesets/guides/vector-tiles-standards/) might be a good place to start.

If you produce vector tiles and use a standard style for drawing them, in theory you could draw the map using any mapping library that supports slippy maps and vector tiles.

I'm going to close this issue since there doesn't appear to be anything actionable here.
